export const WEBUI_CONFIG = {
  shared: {
    outputBucketLabels: {
      "daily-japanese": "日常日本語の出力",
      indonesian: "インドネシア語の出力",
    },
  },
  login: {
    title: "Login — GRKD-Jisho Admin",
    shell: {
      bodyClass: "min-h-dvh bg-porcelain-50 font-grkd-sans text-graphite-900",
      mainClass: "relative min-h-dvh overflow-hidden px-4 py-4 sm:px-6 lg:px-8",
      stageClass: "relative mx-auto flex min-h-[calc(100dvh-2rem)] max-w-7xl items-center",
      shellClass:
        "grid w-full overflow-hidden rounded-modal border border-graphite-180 bg-[oklch(97%_0.012_95/0.82)] shadow-[0_30px_80px_oklch(20%_0.018_255/0.16)] backdrop-blur-sm lg:min-h-[760px] lg:grid-cols-[0.68fr_1.32fr]",
      footerClass: "relative mx-auto mt-6 max-w-7xl px-2 text-center text-caption text-graphite-500 sm:mt-8",
      footerTitle: "GRKD-Jisho Admin",
      footerSuffix: "v0.1.0",
      footerPoweredBy: "Powered by GoRakuDo",
    },
    hero: {
      kicker: "Secure admin access",
      product: "GRKD-Jisho Admin",
      headline: "Calm entry.",
      accent: "Fast access.",
      description:
        "The command surface for the Indonesian-Japanese dictionary bot. If setup is missing, this screen shows the QR onboarding lane.",
      accessModeLabel: "Access mode",
      accessModeBadge: "TOTP secured",
      accessModeCopy: "Built for one human, one server, and a short path back into the dashboard.",
    },
      steps: {
      stepLabels: ["Step 01", "Step 02", "Step 03"],
      setup: [
        "Register the device once with a QR scan.",
        "Use the current six-digit code from your app.",
        "Reset from SSH only when you want a fresh secret.",
      ],
    },
    auth: {
      loading: "Checking authentication setup…",
      loadingFailed: 'Failed to connect. <a href="/auth/login" class="text-royal-blue-600 underline">Retry</a>.',
      laneLabel: "Authentication lane",
      returningTitle: "Returning admin",
      returningCopy: "Open your authenticator app and enter the current 6-digit code to enter the dashboard.",
      returningBadge: "Ready",
      codeLabel: "Authenticator Code",
      codePlaceholder: "000000",
      setupTitle: "First-time setup",
      setupBadge: "Configure once",
      setupCopy: "Scan the code, confirm the 6-digit token, and the admin login becomes ready for next time.",
      setupGuideTitle: "First-time setup",
      setupGuideSteps: [
        "Scan the QR code with your authenticator app.",
        "Enter the six-digit code to finish setup.",
        "Keep the app installed for future logins.",
      ],
      loginGuideTitle: "Quick access",
      loginGuideSteps: [
        "Open your authenticator app.",
        "Use the six-digit code for GRKD-Jisho Admin.",
        "You’re straight into the dashboard.",
      ],
      qrHelp: "Can’t scan? Copy the manual key below into your authenticator app.",
      resetHint: "Lost the app? Run <code class=\"font-grkd-mono text-royal-blue-700\">pnpm auth:reset</code> on the server.",
      submitLogin: "Log In",
      submitSetup: "Verify & Complete Setup",
      submitBusyLogin: "Signing in…",
      submitBusySetup: "Verifying…",
      invalidCode: "Invalid code. Try again with the current 6-digit code from your authenticator app.",
      connectionError: "Connection error. Is the server running?",
      verificationFailed: "Verification failed. Try again.",
      setupRequiredRedirect: "/auth/setup",
    },
    layout: {
      qrWrapClass: "mx-auto w-full max-w-[360px]",
      manualKeyClass: "mx-auto mt-3 block max-w-[360px] rounded-panel border border-royal-blue-100 bg-royal-blue-50 px-3 py-3 text-center font-grkd-mono text-caption leading-6 text-royal-blue-700 break-all select-all",
      formClass: "mx-auto mt-4 w-full max-w-[560px] space-y-3",
      qrCardClass: "hidden mt-6 w-full rounded-panel border border-graphite-180 bg-porcelain-100 p-4",
      authCardClass: "hidden w-full rounded-modal border border-graphite-180 bg-porcelain-50 px-6 py-6 shadow-[0_20px_50px_oklch(20%_0.018_255/0.12)] lg:px-8 lg:py-8",
      loadingClass: "flex items-center gap-3 text-body-sm text-graphite-500",
    },
  },
  prompts: {
    page: {
      libraryLabel: "Prompt Library",
      title: "Scoped prompt control",
      description: "Two output buckets. Each inherits the system baseline until you create a custom override.",
      scopeNavigatorLabel: "Output buckets",
      scopeNavigatorNote: "Select a bucket to inspect its version history. Override the baseline prompt per bucket as needed.",
      selectedScopeLabel: "Selected bucket",
      versionHistoryLabel: "Version history",
      editorScopeLabel: "Scope",
      activeVersionLabel: "Set as active version",
      saving: "Saving...",
      baselineLabel: "Baseline",
      baselineVersionName: "system",
      deleteConfirmPrefix: "Delete prompt version ",
      deleteConfirmSuffix: "? This cannot be undone.",
      resetOverrideConfirmPrefix: "Reset the ",
      resetOverrideConfirmSuffix: " override and fall back to the system baseline?",
      failedToSave: "Failed to save prompt version.",
      createVersion: "Create New Version",
      resetOverride: "Reset Override",
      noOverride: "No override yet",
      noOverrideCopy: "This bucket still inherits the system baseline. Create a new version to specialize it.",
      noActiveVersion: "No active version",
      runtimeFallback: "Runtime fallback",
      inheritedFromDefault: "Baseline",
      loadErrorTitle: "Failed to load prompt scopes",
      loadErrorCopy: "Check the admin API and database connection.",
      scopeCardBaseline: "Baseline",
      scopeCardInherited: "Inherited",
      scopeCardOverrideActive: "Override active",
      activeVersionPrefix: "Active · ",
      noResolvedPrompt: "No resolved prompt",
      createOverrideVersion: "Create New Version",
      editVersion: "Edit version",
      createPromptVersion: "Create new prompt version",
      editPromptVersion: "Edit prompt version",
      loading: "Loading",
      runtimeVersionPrefix: "Runtime version ",
      editorLabel: "Editor",
      previewLabel: "Preview",
      cancel: "Cancel",
      save: "Save Changes",
      edit: "Edit",
      activate: "Activate",
      delete: "Delete",
      templateVariablesLabel: "Template variables",
      routingContractLabel: "Routing contract",
      referenceTableHeaders: {
        variable: "Variable",
        description: "Description",
      },
      status: {
        active: "Active",
        inactive: "Inactive",
      },
    },
    variables: [
      { name: "{{role_key}}", description: "Output bucket used for routing: daily-japanese or indonesian" },
      { name: "{{query}}", description: "The searched word or phrase" },
      { name: "{{dictionary_form}}", description: "Dictionary base form (same as query on direct match)" },
      { name: "{{reading}}", description: "Reading or pronunciation of the query" },
      { name: "{{dictionary_name}}", description: "Name of the dictionary that supplied the entry" },
      { name: "{{definition_json}}", description: "Raw dictionary payload as JSON" },
      { name: "{{prompt_version}}", description: "Current prompt version label" },
    ],
      routing: [
        "System baseline stays public and shared.",
        "Bucket override wins when it exists and is active.",
        "If a bucket has no override, it inherits the system baseline.",
        "Clone/export for general users should use the baseline scope only.",
      ],
  },
  roleSettings: {
    page: {
      title: "Role Settings",
      description: "Configure output bucket bindings, per-role daily search limits, and reset user usage.",
      addRoleLimit: "+ Add Role Limit",
      defaultLimitTitle: "Default Limit",
      defaultLimitEdit: "✎ Edit",
      defaultLimitCopy: "All roles without a custom limit:",
      searchesPerDaySuffix: " searches/day",
      defaultLimitHint: "Owner and Administrator roles are always unlimited.",
      unlimitedLabel: "Unlimited",
      perDaySuffix: " /day",
      resetTitle: "Reset User Usage",
      resetCopy: "Reset a user's search count for today (GMT+7).",
      resetButton: "Reset Usage",
      addBinding: "+ Add Binding",
      bindingsTitle: "Output Bucket Bindings",
      bindingsCopy: "Map Discord role IDs to output buckets for prompt routing.",
      bindingsHint: "日常日本語の出力が優先。どちらにも当たらない場合はインドネシア語に落ちます。複数の Discord role IDs を同じバケットに紐づけられます。",
      roleModalAdd: "Add Role Limit",
      roleModalEditDefault: "Edit Default Limit",
      roleModalEditPrefix: "Edit: ",
      roleModalClose: "✕ Close",
      roleModalCancel: "Cancel",
      roleModalSave: "Save",
      bindingModalTitle: "Edit Output Bucket Binding",
      bindingModalCancel: "Cancel",
      bindingModalSave: "Save",
      emptyRoleLimits: "No custom role limits configured.",
      emptyBindings: "No custom bindings configured. Add Discord role IDs to map them to output buckets.",
      tableHeaders: {
        roleName: "Role Name",
        roleId: "Role ID",
        dailyLimit: "Daily Limit",
        actions: "Actions",
        bindingRoleId: "Discord Role ID",
        bindingBucket: "Output Bucket",
      },
      fieldLabels: {
        roleId: "Discord Role ID *",
        roleLabel: "Role Label (optional)",
        dailyLimit: "Daily Limit *",
        bindingRoleId: "Discord Role ID",
        bindingBucket: "Output Bucket",
        resetUserId: "User ID",
        resetGuildId: "Guild ID",
      },
      placeholders: {
        roleId: "e.g. 123456789012345678",
        roleLabel: "e.g. Moderator",
        dailyLimit: "-1 for unlimited, or 1–99999",
        resetUserId: "e.g. 123456789012345678",
        resetGuildId: "e.g. 987654321098765432",
        bindingRoleId: "e.g. 123456789012345678",
      },
      hints: {
        dailyLimit: "-1 = unlimited. Owner/Admin are always unlimited regardless of this setting.",
      },
      rowBadges: {
        default: "Default",
        protected: "Protected",
      },
      rowActions: {
        edit: "Edit",
        delete: "Delete",
      },
      bindingActions: {
        edit: "✎ Edit",
        delete: "Delete",
      },
      alerts: {
        deleteRoleLimitConfirm: "Delete this role limit? This cannot be undone.",
        deleteBindingConfirm: "Delete this role binding?",
        csrfUnavailableReload: "CSRF token not available. Please reload the page.",
        csrfUnavailable: "CSRF token not available.",
        roleIdRequired: "Discord Role ID is required.",
        userIdRequired: "User ID is required.",
        guildIdRequired: "Guild ID is required.",
        dailyLimitRequired: "Daily Limit is required.",
        dailyLimitInvalid: "Daily Limit must be -1 (unlimited) or between 1 and 99999.",
      },
      resetMessages: {
        successPrefix: "✓ Usage reset for user ",
        errorPrefix: "Error: ",
        failed: "Failed to reset usage. Check console.",
      },
    },
  },
} as const;
